// <auto-generated />
using System;
using AquaAlertApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaAlertApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106081406_MakeTimestampsTimestamptz")]
    partial class MakeTimestampsTimestamptz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaAlertApi.Data.CMS.Cohort", b =>
                {
                    b.Property<Guid>("CohortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CohortId");

                    b.ToTable("Cohorts");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.HasKey("CompanyId");

                    b.HasIndex("PlanId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.CompanyCohort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyCohorts");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.CompanyFeature", b =>
                {
                    b.Property<Guid>("CompanyFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CompanyFeatureId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FeatureId");

                    b.ToTable("CompanyFeatures");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.Feature", b =>
                {
                    b.Property<Guid>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DefaultEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAddOn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("FeatureId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.FeatureRollout", b =>
                {
                    b.Property<Guid>("RolloutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CohortId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parameter")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RolloutType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RolloutId");

                    b.HasIndex("CohortId");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeatureRollouts");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.Plan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.PlanFeature", b =>
                {
                    b.Property<Guid>("PlanFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.HasKey("PlanFeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanFeatures");
                });

            modelBuilder.Entity("AquaAlertApi.Data.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapacityLiters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("capacity_liters");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tanks_pkey");

                    b.ToTable("tanks", (string)null);
                });

            modelBuilder.Entity("AquaAlertApi.Data.WaterLevelLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BatteryVoltage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("battery_voltage");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LoggedAtLocal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at_local");

                    b.Property<decimal?>("PercentageFull")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage_full");

                    b.Property<string>("SensorStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sensor_status")
                        .HasDefaultValueSql("'OK'::character varying");

                    b.Property<int>("TankId")
                        .HasColumnType("integer")
                        .HasColumnName("tank_id");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TemperatureC")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_c");

                    b.Property<decimal>("WaterLevelCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("water_level_cm");

                    b.Property<decimal?>("WaterVolumeLiters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("water_volume_liters");

                    b.HasKey("Id")
                        .HasName("water_level_logs_pkey");

                    b.HasIndex("TankId");

                    b.ToTable("water_level_logs", (string)null);
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.Company", b =>
                {
                    b.HasOne("AquaAlertApi.Data.CMS.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.CompanyCohort", b =>
                {
                    b.HasOne("AquaAlertApi.Data.CMS.Cohort", "Cohort")
                        .WithMany("CompanyCohorts")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquaAlertApi.Data.CMS.Company", "Company")
                        .WithMany("CompanyCohorts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.CompanyFeature", b =>
                {
                    b.HasOne("AquaAlertApi.Data.CMS.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquaAlertApi.Data.CMS.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.FeatureRollout", b =>
                {
                    b.HasOne("AquaAlertApi.Data.CMS.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId");

                    b.HasOne("AquaAlertApi.Data.CMS.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.PlanFeature", b =>
                {
                    b.HasOne("AquaAlertApi.Data.CMS.Feature", "Feature")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AquaAlertApi.Data.CMS.Plan", "Plan")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("AquaAlertApi.Data.WaterLevelLog", b =>
                {
                    b.HasOne("AquaAlertApi.Data.Tank", "Tank")
                        .WithMany("WaterLevelLogs")
                        .HasForeignKey("TankId")
                        .IsRequired()
                        .HasConstraintName("fk_tank");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.Cohort", b =>
                {
                    b.Navigation("CompanyCohorts");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.Company", b =>
                {
                    b.Navigation("CompanyCohorts");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.Feature", b =>
                {
                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("AquaAlertApi.Data.CMS.Plan", b =>
                {
                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("AquaAlertApi.Data.Tank", b =>
                {
                    b.Navigation("WaterLevelLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
