services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Default RabbitMQ port
      - "15672:15672" # Management Plugin port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq # Persist RabbitMQ data
      - ./rabbitmq/logs:/var/log/rabbitmq # Persist RabbitMQ logs
    restart: always
    networks:
      - aquaalert_network
  aquaalertapi:
    #image: aquaalertapi-image
    image: emmanueljomer/aquaalertapi:latest
    container_name: aquaalertapi
    #build:
    #  context: .
    # dockerfile: Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - aquaalert_network
networks:
  aquaalert_network:
    driver: bridge
